FROM playgali/faas_base:latest-armhf
MAINTAINER Galileo Martinez "playgali@gmail.com"
ENV REFRESHED_AT 2018-Apr-15

RUN [ "cross-build-start" ]

RUN apk add --no-cache pwgen

RUN [ "cross-build-end" ]

ENV fprocess="xargs pwgen -s"
HEALTHCHECK --interval=5s CMD [ -e /tmp/.lock ] || exit 1
CMD ["fwatchdog"]
